<a href="https://colab.research.google.com/github/Tikaanggrn/UTS_MACHINE_LEARNING2023-2024/blob/main/JAWABAN_UTS_MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries
!pip install --upgrade kneed

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, silhouette_score
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import tree
from kneed import KneeLocator
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

Soal No.2

In [ ]:
# Memisahkan bagian atribut prediktor dengan label data menjadi dua variabel terpisah
url = "https://raw.githubusercontent.com/isnanmulia/lecture-datasets/main/mobileprice_modified.csv"
data = pd.read_csv(url)

# Memisahkan atribut prediktor (fitur) dari label data
X = data.drop(columns=['price_range'])
y = data['price_range']

In [ ]:
# Menangani missing values dengan SimpleImputer (strategi: median)
imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X)

In [ ]:
# Inisialisasi MinMaxScaler
scaler = MinMaxScaler()

# Menerapkan MinMaxScaler pada atribut prediktor (fitur)
X = scaler.fit_transform(X)

In [ ]:
# Menerapkan StandardScaler untuk standarisasi atribut prediktor
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

In [ ]:
# Menampilkan statistik deskriptif sebelum preprocessing
print("Statistik Deskriptif Sebelum Preprocessing:")
print(pd.DataFrame(X, columns=data.columns.drop('price_range')).describe())

# Menampilkan statistik deskriptif setelah pengisian Missing Values dan standarisasi
print("\nStatistik Deskriptif Setelah Pengisian Missing Values dan Standarisasi:")
print(pd.DataFrame(X_scaled, columns=data.columns.drop('price_range')).describe())

Statistik Deskriptif Sebelum Preprocessing:
       battery_power       blue  clock_speed     dual_sim           fc  \
count    1990.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean        0.492230     0.4950     0.408900     0.509500     0.226816   
std         0.293705     0.5001     0.326402     0.500035     0.228497   
min         0.000000     0.0000     0.000000     0.000000     0.000000   
25%         0.233300     0.0000     0.080000     0.000000     0.052632   
50%         0.483634     0.0000     0.400000     1.000000     0.157895   
75%         0.744155     1.0000     0.680000     1.000000     0.368421   
max         1.000000     1.0000     1.000000     1.000000     1.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  \
count  2000.000000  1990.000000  2000.000000  1990.000000  2000.000000   
mean      0.521500     0.483676     0.446389     0.502869     0.502929   
std       0.499662     0.292523     0.320462     0.295059     0.326

Soal No.3

In [ ]:
# Memisahkan atribut prediktor (X_scaled) dari label data (y)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
# Inisialisasi model Decision Tree
model = DecisionTreeClassifier(random_state=42)

# Latih model pada data pelatihan
model.fit(X_train, y_train)


DecisionTreeClassifier(random_state=42)

In [ ]:

#Melakukan prediksi pada data pengujian
y_pred = model.predict(X_test)

In [ ]:
  # Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)

# Menampilkan confusion matrix
print("Confusion Matrix:")
print(cm)

# Menampilkan akurasi
print("Akurasi: {:.2f}%".format(accuracy * 100))

Confusion Matrix:
[[90 15  0  0]
 [ 5 74 12  0]
 [ 0 16 64 12]
 [ 0  0 13 99]]
Akurasi: 81.75%


Soal No.4

In [ ]:
# Inisialisasi model K-Means dengan jumlah cluster yang diinginkan
n_clusters = 4  # Misalnya, ingin 4 cluster
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)

# Latih model K-Means pada data
kmeans.fit(X_scaled)


KMeans(n_clusters=4, n_init=10, random_state=42)

In [ ]:
# Melakukan prediksi cluster pada data
cluster_labels = kmeans.predict(X_scaled)


In [ ]:
# Mendapatkan label cluster untuk setiap sampel
cluster_labels = kmeans.labels_

In [ ]:
# Menghitung Silhouette Score dari model clustering
silhouette_avg = silhouette_score(X_scaled, cluster_labels)

# Menampilkan Silhouette Score
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.05830501834188593
